
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  timeout: 5000
  username: root
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: snoopbot_development

test:
  <<: *default
  database: snoopbot_test

production:
  <<: *default
  database: snoopbot_production
